// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NguyenNGocLongVu33.Migrations
{
    [DbContext(typeof(LTQLDD))]
    [Migration("20230621112306_LV")]
    partial class LV
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("NguyenNGocLongVu_33.Models.LopHoc", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaLop");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("NguyenNGocLongVu_33.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSinhvien")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaSinhvien");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("NguyenNGocLongVu_33.Models.TTSV", b =>
                {
                    b.Property<string>("MaSinhvien")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaSinhvien");

                    b.HasIndex("MaLop");

                    b.ToTable("TTSV");
                });

            modelBuilder.Entity("NguyenNGocLongVu_33.Models.TTSV", b =>
                {
                    b.HasOne("NguyenNGocLongVu_33.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });
#pragma warning restore 612, 618
        }
    }
}
